# Generated by Django 2.2.7 on 2019-12-11 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_squashed_0004_auto_20191119_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
