# Generated by Django 2.2.7 on 2019-12-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191213_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
