# Generated by Django 2.2.7 on 2019-12-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField(default='')),
                ('technology', models.CharField(max_length=20)),
                ('project_image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='documents/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=False)),
                ('sub_url', models.CharField(max_length=100)),
            ],
        ),
    ]
