# Generated by Django 2.2.7 on 2019-12-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sub_url',
        ),
    ]
