# Generated by Django 2.2.7 on 2019-12-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191213_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
    ]
