# Generated by Django 3.0.4 on 2020-03-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20191215_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
