# Generated by Django 3.0.3 on 2020-02-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_link_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='project_image',
            new_name='link_image',
        ),
    ]
