# Generated by Django 3.0.3 on 2020-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20200218_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Text Body',
                'verbose_name_plural': 'Text Bodies',
            },
        ),
        migrations.AlterField(
            model_name='link',
            name='link_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
