#!/bin/sh

psql -U postgres -c "CREATE USER $DJANGO_POSTGRES_USER PASSWORD '$DJANGO_POSTGRES_PASSWORD'"
psql -U postgres -c "CREATE DATABASE $DJANGO_POSTGRES_DB OWNER $DJANGO_POSTGRES_USER"
psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DJANGO_POSTGRES_DB TO $DJANGO_POSTGRES_USER"
